//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prato
    {
        public int pratoId { get; set; }
        public int restId { get; set; }
        public string pratoName { get; set; }
        public double pratoPreco { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
        public virtual Restaurante Restaurante1 { get; set; }
    }
}
